### ISSUE TITLE
Climate broken: AttributeError: 'Vehicle' object has no attribute 'region'

### ISSUE THREAD

**Issue by JamesT42** [fuatakgun/kia_uvo#125]
Hi!

climate service is broken in latest version

```
2021-11-13 14:21:37 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'Vehicle' object has no attribute 'region'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/kia_uvo/__init__.py", line 91, in async_handle_start_climate
    await vehicle.start_climate(set_temp, duration, defrost, climate, heating)
  File "/config/custom_components/kia_uvo/Vehicle.py", line 138, in start_climate
    if(self.engine_type == VEHICLE_ENGINE_TYPE.EV and self.region == REGION_CANADA):
AttributeError: 'Vehicle' object has no attribute 'region'
2021-11-13 14:21:37 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2967215264] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 523, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1243, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/kia_uvo/__init__.py", line 91, in async_handle_start_climate
    await vehicle.start_climate(set_temp, duration, defrost, climate, heating)
  File "/config/custom_components/kia_uvo/Vehicle.py", line 138, in start_climate
    if(self.engine_type == VEHICLE_ENGINE_TYPE.EV and self.region == REGION_CANADA):
AttributeError: 'Vehicle' object has no attribute 'region'


```

**Comment by cdnninja** [comment]
What region and brand?

**Comment by JamesT42** [comment]
EU, Hyundai Ioniq 5

**Comment by cdnninja** [comment]
Could you try remove and readd the integration? If that solves it I think I know the issue.

**Comment by JamesT42** [comment]
Well I removed it, and now I can't log in to readd. "Login failed into Kia Uvo / Hyundai Bluelink Servers. Please use official Kia Uvo app to logout and log back in and try again!"
I've rechecked the username and password several times.

**Comment by cdnninja** [comment]
Well that is concerning.  Could you enable debug logging outlined on GitHub and post the error?  Wondering if it’s the new login issue we have seen.

**Comment by cdnninja** [comment]
@JamesT42 the login issue should be solved if it was the larger EU issue.  Please re-open if this is still an issue.

**Comment by JamesT42** [comment]
I was now able to delete the integration an add it again. But the error is still there.

```
2021-11-14 23:58:36 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'Vehicle' object has no attribute 'region'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/kia_uvo/__init__.py", line 91, in async_handle_start_climate
    await vehicle.start_climate(set_temp, duration, defrost, climate, heating)
  File "/config/custom_components/kia_uvo/Vehicle.py", line 150, in start_climate
    if self.engine_type == VEHICLE_ENGINE_TYPE.EV and self.region == REGION_CANADA:
AttributeError: 'Vehicle' object has no attribute 'region'
2021-11-14 23:58:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2969353544] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 523, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1243, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/kia_uvo/__init__.py", line 91, in async_handle_start_climate
    await vehicle.start_climate(set_temp, duration, defrost, climate, heating)
  File "/config/custom_components/kia_uvo/Vehicle.py", line 150, in start_climate
    if self.engine_type == VEHICLE_ENGINE_TYPE.EV and self.region == REGION_CANADA:
AttributeError: 'Vehicle' object has no attribute 'region'
```

**Comment by fuatakgun** [comment]
@cdnninja this seems to be a problem

**Comment by cdnninja** [comment]
Mistake on my side.   I put in a fix that should solve this.   Are you able to retest?

**Comment by JamesT42** [comment]
Yes thank you it is fixed now.
