### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by holdestmade** [fuatakgun/kia_uvo#13]
Just had 2 occurrences of this in my log:

```
Logger: homeassistant.util.async_
Source: util/async_.py:131
First occurred: 12:12:06 (2 occurrences)
Last logged: 12:42:06

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for kia_uvo doing I/O at custom_components/kia_uvo/KiaUvoApi.py, line 37: response = requests.post(url, headers=headers, json=payload)
```

0adf47f

**Comment by holdestmade** [comment]
Also getting this on update:

```
Logger: homeassistant
Source: custom_components/kia_uvo/KiaUvoApi.py:190
First occurred: 12:53:58 (1 occurrences)
Last logged: 12:53:58

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 392, in _async_run
    return await self.script.async_run(variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1195, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 341, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/kia_uvo/__init__.py", line 43, in async_handle_force_update
    await vehicle.async_force_update()
  File "/config/custom_components/kia_uvo/Vehicle.py", line 50, in async_force_update
    await self.async_update()
  File "/config/custom_components/kia_uvo/Vehicle.py", line 38, in async_update
    self.vehicle_data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApi.py", line 190, in get_cached_vehicle_status
    return response["resMsg"]["vehicleStatusInfo"]
KeyError: 'resMsg'
```

**Comment by holdestmade** [comment]
I restarted and all the entities were unavailable. I removed the integration and re-added and all works OK again, I'll keep an eye out in the logs

**Comment by fuatakgun** [comment]
as of now, problem 1 requires creating an external library, which is in roadmap with low priority.
problem 2 might be about token expiration, next time, please enable debugging and share your full home assistant logs

**Comment by holdestmade** [comment]
OK thanks

**Comment by fuatakgun** [comment]
please get the latest version, warning should disappear and token expiration should be fixed.

**Comment by holdestmade** [comment]
No had any more of these so will close
