### ISSUE TITLE
Add Handler for Old Models

### ISSUE THREAD

**Issue by stboch** [fuatakgun/kia_uvo#181]
**Region and Brand of car**
USA Hyunadi

**Describe the bug**
Two Parts, 1. handeling missing enrollmentDate 
2. Evaluate response from vehicle_status to ensure feature is available.  

**Debug logs if an error occurred**
2021-11-25 09:37:42 DEBUG (SyncWorker_12) [custom_components.kia_uvo.HyundaiBlueLinkAPIUSA] kia_uvo - get_cached_vehicle_status response {'errorSubCode': 'GEN', 'systemName': 'BLODS', 'errorSubMessage': 'Feature Status is OFF', 'errorMessage': "We're sorry, this feature is not available according to your latest subscription status.  Please visit the owners website to view and update subscription.", 'errorCode': 502}
2021-11-25 09:37:42 ERROR (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Exception in update : 'vehicleStatus' - traceback: Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/Vehicle.py", line 58, in update
    self.vehicle_data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py", line 151, in get_cached_vehicle_status
    vehicle_status["vehicleStatus"] = response["vehicleStatus"]
KeyError: 'vehicleStatus'

**Expected behavior**
Ignore Devices/Vehicles that lack required features.

**Comment by cdnninja** [comment]
Do you have a second car you are trying to use this for but being caught up by the first?

**Comment by cdnninja** [comment]
A new version exists under #221 that is a bit of a rewrite that may solve this.  Testers are appreciated.

**Comment by cdnninja** [comment]
2.0 is out for alpha testing.  This should be solved in it.  Closing this for now.  Please comment/open a new request if this remains.
