### ISSUE TITLE
Start A/C, 'Vehicle' object has no attribute 'region'

### ISSUE THREAD

**Issue by AlexJHuber** [fuatakgun/kia_uvo#203]
**Region and Brand of car**
EU(NL) Kia E-Niro

**Describe the bug**
I've created a button in Lovelace that calls the service 'kia_uvo.start_climate'.
Every time I press the button and try to call the service it gives a warning 
'Start A/C, 'Vehicle' object has no attribute 'region'' 

**Debug logs if an error occurred**
2021-12-09 20:03:12 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547622581200] 'Vehicle' object has no attribute 'region'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/kia_uvo/__init__.py", line 91, in async_handle_start_climate
    await vehicle.start_climate(set_temp, duration, defrost, climate, heating)
  File "/config/custom_components/kia_uvo/Vehicle.py", line 138, in start_climate
    if(self.engine_type == VEHICLE_ENGINE_TYPE.EV and self.region == REGION_CANADA):
AttributeError: 'Vehicle' object has no attribute 'region'

**Comment by cdnninja** [comment]
This was introduced by me.    I think removing and readding the integration solves it.   When I get a chance I can look at solving for others.

**Comment by AlexJHuber** [comment]
I just uninstalled the integration. Restarted HA and installed the integration again. Unfortunately it still gives me the same message.

**Comment by fuatakgun** [comment]
hey, I have the latest version of integration and I do not have this issue and I can clearly see that your code is not up to date.

Vehicle.py - line 138 does not have `if(self.engine_type == VEHICLE_ENGINE_TYPE.EV and self.region == REGION_CANADA):`
It should be around 193, please be sure that you have the latest version.

**Comment by AlexJHuber** [comment]
Aah yes. I know what I did wrong. I reinstalled the integration but didn't check HACS for updates.
Now it works like a charm. Thanks for the support!

Cheers, A
