### ISSUE TITLE
Cannot log in using form

### ISSUE THREAD

**Issue by DutchessNicole** [fuatakgun/kia_uvo#212]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
EU, E-Niro MY21

**Describe the bug**

When configuring login credentials on the configuration form and submitting, the form times out after about a minute. The HA logs specifiy that the connection timed out.

**Debug logs if an error occurred**
```
2021-12-18 12:24:53 ERROR (MainThread) [custom_components.kia_uvo.config_flow] kia_uvo Exception in kia_uvo login : ('Connection aborted.', TimeoutE
rror(110, 'Operation timed out')) - traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(110, 'Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 155, in async_step_user
    self.token = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 101, in login
    self.device_id, self.stamp = self.get_device_id()
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 167, in get_device_id
    response = requests.post(url, headers=headers, json=payload)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(110, 'Operation timed out'))
```

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.m

**To Reproduce**
1. Go to integration page
2. Add the Kia UVO/ Hyundai Bluelink integration
3. Enter credentials into the form and submit
4. Form returns with an error, HA log shows the above.

**Expected behavior**
Form submits and manages to reach the API server.

**Screenshots**

**Additional context**
API endpoint seems unavaiable, but I cannot tell why.

```
$ mtr -r -c 3 eu-account.kia.com
Start: 2021-12-18T13:01:10+0100
HOST: MintyNicole20               Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- _gateway                   0.0%     3    0.2   0.2   0.2   0.3   0.1
  2.|-- 192.168.2.1                0.0%     3    0.7   0.6   0.5   0.7   0.1
  3.|-- 002-208-158-163.dynamic.c  0.0%     3    1.2   1.4   1.2   1.5   0.2
  4.|-- cn-asd-kl-cr15-be2003-201  0.0%     3    2.6   2.4   2.1   2.6   0.2
  5.|-- hu0-1-0-7.ccr21.ams04.atl  0.0%     3    2.8   2.7   2.6   2.8   0.1
  6.|-- bt.ams04.atlas.cogentco.c  0.0%     3    2.5   2.4   2.3   2.5   0.1
  7.|-- t2c3-et-5-0-2-0.nl-ams2.g  0.0%     3    2.8   2.8   2.7   2.9   0.1
  8.|-- t2c3-xe-11-0-0.de-fra.gia  0.0%     3   11.0  22.5  10.8  45.6  20.0
  9.|-- ???                       100.0     3    0.0   0.0   0.0   0.0   0.0

```

```
$ nmap -Pn eu-account.kia.com
Starting Nmap 7.80 ( https://nmap.org ) at 2021-12-18 13:01 CET
Nmap scan report for eu-account.kia.com (185.106.8.62)
Host is up (0.011s latency).
Not shown: 999 filtered ports
PORT    STATE SERVICE
443/tcp open  https

Nmap done: 1 IP address (1 host up) scanned in 30.49 seconds

```
Server does not respond to ping requests but it does seem to have the HTTPS endpoint open.

I see the same pattern from a different server I own.

**Comment by fuatakgun** [comment]
Can you enable debug logs and share them please?

**Comment by DutchessNicole** [comment]
```
2021-12-20 13:39:27 ERROR (MainThread) [custom_components.kia_uvo.config_flow] kia_uvo Exception in kia_uvo login : HTTPSConnectionPool(host='prd.eu-ccapi.kia.com', port=8080): Max retries exceeded with url: /api/v1/spa/notifications/register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8fe118e0>: Failed to establish a new connection: [Errno 110] Operation timed out')) - traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8fe118e0>: Failed to establish a new connection: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='prd.eu-ccapi.kia.com', port=8080): Max retries exceeded with url: /api/v1/spa/notifications/register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8fe118e0>: Failed to establish a new connection: [Errno 110] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 155, in async_step_user
    self.token = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 101, in login
    self.device_id, self.stamp = self.get_device_id()
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 167, in get_device_id
    response = requests.post(url, headers=headers, json=payload)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='prd.eu-ccapi.kia.com', port=8080): Max retries exceeded with url: /api/v1/spa/notifications/register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8fe118e0>: Failed to establish a new connection: [Errno 110] Operation timed out'))
```
 with these settings. Unfortunately it doesn't give much more information since debug was already set for the initial post
```
default: error
logs:
  custom_components.kia_uvo: debug
```
