### ISSUE TITLE
Integration fails to start after HA restart

### ISSUE THREAD

**Issue by woody55uk** [fuatakgun/kia_uvo#272]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
UK
Hyundai Kona EV

**Describe the bug**
The integration was working fine until I restarted HA a short while ago, when all of the entities became unavailable. I don't think the only change I had made prior to the restart could have been responsible (I added a simple systemmonitor sensor to my config). I've since removed the systemmonitor sensor and the error still remains. Ther are two enties in the logs:

This error originated from a custom integration.

Logger: custom_components.kia_uvo.Vehicle
Source: custom_components/kia_uvo/Vehicle.py:81
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 15:21:33 (1 occurrences)
Last logged: 15:21:33

kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 427, in get_cached_vehicle_status return response["resMsg"]["vehicleStatusInfo"] TypeError: string indices must be integers

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/kia_uvo/__init__.py:207
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 15:21:33 (1 occurrences)
Last logged: 15:21:33

Error setting up entry hy@mikewoods.net for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/kia_uvo/__init__.py", line 218, in async_setup_entry
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 207, in update
    datetime.now(local_timezone) - vehicle.last_updated
TypeError: can't subtract offset-naive and offset-aware datetimes

**To Reproduce**
Happens whenever HA restarted - no other steps needed.

**Expected behavior**
n/a

**Screenshots**
n/a

**Additional context**
n/a

**Comment by woody55uk** [comment]
The app is working fine, and has been throughout. I've just restarted HA again and still no joy. I'll keep monitoring and report back here on any change.
