### ISSUE TITLE
kia_uvo - Exception in force update : string indices must be integers

### ISSUE THREAD

**Issue by holdestmade** [fuatakgun/kia_uvo#29]
Getting this on attempted update:

Have migrated to Kia Account and has been working fine for a while but no longer working

`kia_uvo - Exception in force update : string indices must be integers`

```
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/__init__.py", line 80, in update
    await vehicle.update()
  File "/config/custom_components/kia_uvo/Vehicle.py", line 41, in update
    self.vehicle_data = await self.hass.async_add_executor_job(self.kia_uvo_api.get_cached_vehicle_status, self.token)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApi.py", line 190, in get_cached_vehicle_status
    return response["resMsg"]["vehicleStatusInfo"]
TypeError: string indices must be integers
```

**Comment by m4n63** [comment]
I am also getting this error in my log, several times each day.

Debug gives a good hint:
```
DEBUG (SyncWorker_10) [custom_components.kia_uvo.KiaUvoApi] kia_uvo - get_cached_vehicle_status response {'retCode': 'F', 'resCode': '5031', 'resMsg': 'Unavailable remote control - Service Temporary Unavailable', 'msgId': '***MASKED***'}
```

**Comment by m4n63** [comment]
approx 50% (ish) of the queries get through ok for me though..
For what it is worth, I will reduce the query i my installation to every 30min and see it the error goes away.

**Comment by m4n63** [comment]
reducing the query does not resolve this for me, I still get quite a few Failures with status code "5031". Right now my settings are:
```
DEFAULT_SCAN_INTERVAL = timedelta(minutes=30)
FORCE_SCAN_INTERVAL = timedelta(minutes=300)
SCAN_AFTER_LOCK_INTERVAL = 60
SCAN_AFTER_LOCK_COUNT = 4
NO_FORCE_SCAN_HOUR_START = 23
NO_FORCE_SCAN_HOUR_FINISH = 6
```
will reduce them even more and see it that helps...

**Comment by m4n63** [comment]
I amended as follows:
```
DEFAULT_SCAN_INTERVAL = timedelta(minutes=32)
FORCE_SCAN_INTERVAL = timedelta(minutes=305)
SCAN_AFTER_LOCK_INTERVAL = 61
SCAN_AFTER_LOCK_COUNT = 4
NO_FORCE_SCAN_HOUR_START = 23
NO_FORCE_SCAN_HOUR_FINISH = 6
```
Now I only get the occasional Failure... This afternoon it looks like this for example:
```
2021-05-08 12:04:10 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 12:36:58 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 13:09:11 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 13:40:53 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 14:12:43 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 14:44:41 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 15:16:54 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 15:48:52 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 16:20:56 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 16:52:43 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 17:24:47 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 17:56:52 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 18:29:04 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 19:00:48 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 19:32:43 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
2021-05-08 20:04:17 DEBUG get_cached_vehicle_status response {'retCode': 'F', 'resCode': '5031', 'resMsg': 'Unavailable
2021-05-08 20:36:38 DEBUG get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo':
```
I guess there is not much to do about it, perhaps there is some global limit set on their end, that returns 5031 when there are a bit too many queries at the same time towards their servers...
The code could potentially be enhanced though to capture the Failure and log a simple Error line and exit directly instead of trying to parse the response. 
Or... perhaps the integration could schedule a retry after a minute or so a couple of times in case of  a 5031 status

Just my 2 cents, and thanks for the integration!
:-)

**Comment by fuatakgun** [comment]
in my setup, update is being executed in every 10 minutes and i have received this error only once in last 2 days.
I will keep this issue open and will track the trend.

Moreover, I agree that we should only process when there is a response with retCode S (assuming/hoping it means successful) :) this will go into improvements bucket :)

**Comment by badguy99** [comment]
I've had to back mine back off to every 30 minutes - I don't know if there is a difference between Android and iOS apps, and calls they might do in the background. I use iOS and use it to change the schedule charging fairly regularly and that would be using the same account details.

**Comment by fuatakgun** [comment]
I have updated code base to fail silently rather than breaking the data. You can get the latest code base, observe couple of days and share your results.

**Comment by fuatakgun** [comment]
any update here, anyone getting complete disaster when this had happened. If it is not failing apart, i think we can resolve this. please let me know other way around.

**Comment by m4n63** [comment]
Mine has been running stable now with the following settings:
scan interval:31
force interval: 121
On top of this I do run the occasional manual update as well which also works fine. 
So no issues right now for me.
