### ISSUE TITLE
externalAPI configuration fails

### ISSUE THREAD

**Issue by MrDadoo** [fuatakgun/kia_uvo#295]
**Region and Brand of car**
Kia Europe

**Describe the bug**
when adding the integration to HA 
config_flow reports success but configuration fails. 

![D78A1650-9A8B-42C7-A18A-73F4BCF342F8](https://user-images.githubusercontent.com/18407340/153477253-a1edfb6d-1b3e-4ae4-890a-5183105384ff.jpeg)

**Debug logs if an error occurred**
2022-02-10 19:46:58 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data: string indices must be integers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 81, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 104, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 86, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 48, in initialize
    vehicles = self.api.get_vehicles(self.token)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 149, in get_vehicles
    for entry in response["resMsg"]["vehicles"]:
TypeError: string indices must be integers
2022-02-10 19:46:58 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 6.839 seconds (success: False)

**Comment by fuatakgun** [comment]
There was an overall outage in Kia EU servers, can you give a fresh try?

**Comment by MrDadoo** [comment]
I also found this in the logs  that might be helpful.

`DEBUG (SyncWorker_3) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Get Vehicles Response 
`{'retCode': 'F', 'resCode': '4002', 'resMsg': 'Invalid request body - deviceId is not exist. ', 'msgId': '197fd018-dd22-4e20-83f7-da12de7c01bb'}`

After this we get the `Unexpected error fetching kia_uvo data: string indices must be integers` error

`response["resMsg"]["vehicles"]:
TypeError: string indices must be integers`

which is understandable as the response were not the expected one.

**Comment by L44RS** [comment]
I can confirm this has been fixed in version 1.5. Thanks!

**Comment by MrDadoo** [comment]
I trried this new version.

When adding integration I got error "Device is already configured"

I did remove old integration, restarted ha, copied new files and when adding configureation - after entering username/password - I get this error.

**Comment by cdnninja** [comment]
If you remove the integration I think a restart of HA is required.   This version supports in place upgrades though from the standard release.

**Comment by MrDadoo** [comment]
Still got "Device is already configured"
