### ISSUE TITLE
Issue setting up sensors (no gas Mode range on pure EV)

### ISSUE THREAD

**Issue by badguy99** [fuatakgun/kia_uvo#3]
First of all, I just wanted to say a massive thank you for taking the time to put this together. I was really hoping someone would, and really appreciate it.

When I installed it, I got an exception setting up the sensors:
```
2021-04-10 17:38:54 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.kia_uvo
2021-04-10 17:38:54 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.kia_uvo
2021-04-10 17:38:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.kia_uvo
2021-04-10 17:38:54 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.niro_ev_19_hood
2021-04-10 17:38:54 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.niro_ev_19_trunk
2021-04-10 17:38:54 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.niro_ev_19_door_front_left
2021-04-10 17:38:54 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.niro_ev_19_door_front_right
2021-04-10 17:38:54 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.niro_ev_19_door_rear_left
2021-04-10 17:38:54 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.niro_ev_19_door_rear_right
2021-04-10 17:38:54 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.niro_ev_19_door_lock
2021-04-10 17:38:54 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.niro_ev_19_engine
2021-04-10 17:38:54 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.niro_ev_19_data
2021-04-10 17:38:54 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new device_tracker.kia_uvo entity: device_tracker.niro_ev_19_location
2021-04-10 17:38:54 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up kia_uvo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/kia_uvo/sensor.py", line 16, in async_setup_entry
    ("fuelDrivingDistance", "Range by Fuel", vehicle.vehicle_data["vehicleStatus"]["evStatus"]["drvDistance"][0]["rangeByFuel"]["gasModeRange"]["value"], "km", "mdi:road-variant", None),
KeyError: 'gasModeRange'
```
Our Kia is an eNiro 4, so pure electric, so I'm not surprised by this. I guess it just needs handling.

When I look at binary_sensor.niro_ev_19_data the data seems to be all there as attributes, so I guess it is just the creation of the sensors, with a way to handle not having gasModeRange for pure EVs

```
  evStatus:
    batteryCharge: false
    batteryStatus: 47
    batteryPlugin: 0
    remainTime2:
      etc1:
        value: 41
        unit: 1
      etc2:
        value: 1180
        unit: 1
      etc3:
        value: 400
        unit: 1
      atc:
        value: 380
        unit: 1
    drvDistance:
      - rangeByFuel:
          evModeRange:
            value: 123
            unit: 3
          totalAvailableRange:
            value: 123
            unit: 3
        type: 2
```

**Comment by fuatakgun** [comment]
thanks for reaching out, I own a Kia Niro Phev and my car has EV range and gas range. Apparently, you own an Kira Niro EV so you dont have gasModeRange attribute, Let me fix it, i will update here soon

**Comment by fuatakgun** [comment]
can you please retry? It should be fixed with latest version

**Comment by badguy99** [comment]
That worked great. Thank you!

**Comment by fuatakgun** [comment]
Welcome
