### ISSUE TITLE
set_charge_limits does nothing

### ISSUE THREAD

**Issue by zadigre** [fuatakgun/kia_uvo#307]
I have a Kona Electric. 
I'm in Canada

set_charge_limits does not work. it doesn't set anything. 
also errors in the core log shortly after I run the service from the developer menu:
2022-03-15 06:46:13 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2022-03-15 06:46:13 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2022-03-15 06:46:29 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/Vehicle.py", line 107, in check_action_completed_loop
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiCA.py", line 376, in check_last_action_status
    response["result"]["transaction"]["apiStatusCode"] != "null"
KeyError: 'result'

settings this in the bluelink app works fine.

**Comment by FuzzyMistborn** [comment]
I was wondering the same thing (Hyundai Ioniq 5 here).  Looks like this is the answer from the readme:

> set_charge_limits: You can control your charging capacity limits using this services **(USA Kia Only)**

So won't work on the Kona.  Though I am curious as to why it doesn't work.

**Comment by zadigre** [comment]
@FuzzyMistborn 
yes I saw this after posting. 
it's available in the (Canadian) bluelink... thus I'm wondering why it's not available in Home Assistant.

**Comment by cdnninja** [comment]
I have taken a few weeks of downtime on this.   I can take a look at this one.  Most missing items like this have been because I can't test. I have a ICE Canadian car. 

If willing to test we should be able to get this added pretty easily!

**Comment by zadigre** [comment]
> If willing to test we should be able to get this added pretty easily!

I can test. Besides enabling log debug mode. Do you need anything else?

**Comment by cdnninja** [comment]
Please copy this version of the CA api to your local system and test: 

https://github.com/fuatakgun/kia_uvo/pull/311

**Comment by FuzzyMistborn** [comment]
Would the same work for the US (or should I give it a try)?

**Comment by cdnninja** [comment]
What type of car for USA?

**Comment by FuzzyMistborn** [comment]
Ioniq5

**Comment by zadigre** [comment]
> Please copy this version of the CA api to your local system and test:
> 
> #311

@cdnninja 
downloaded the new file to my custom folder... restarted HA.
I get a "unknown error" in the UI
and get this in the CORE log:
```

2022-04-05 09:13:36 DEBUG (SyncWorker_6) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Received Pin validation response <Response [200]>
2022-04-05 09:13:36 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: unhashable type: 'dict'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 582, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/__init__.py", line 111, in async_handle_set_charge_limits
    await vehicle.set_charge_limits(ac_limit, dc_limit)
  File "/config/custom_components/kia_uvo/Vehicle.py", line 247, in set_charge_limits
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiCA.py", line 373, in set_charge_limits
    "tsoc": {{
TypeError: unhashable type: 'dict'
2022-04-05 09:13:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139820170685984] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 630, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1275, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 582, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/__init__.py", line 111, in async_handle_set_charge_limits
    await vehicle.set_charge_limits(ac_limit, dc_limit)
  File "/config/custom_components/kia_uvo/Vehicle.py", line 247, in set_charge_limits
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiCA.py", line 373, in set_charge_limits
    "tsoc": {{
TypeError: unhashable type: 'dict'
```

I restored the previous file, restarted HA... I do not get the error... but it still does nothing.

**Comment by zadigre** [comment]
@cdnninja 
here's what I get with the "original" file. 
```
2022-04-05 09:21:45 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2022-04-05 09:21:45 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2022-04-05 09:22:01 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/Vehicle.py", line 107, in check_action_completed_loop
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiCA.py", line 376, in check_last_action_status
    response["result"]["transaction"]["apiStatusCode"] != "null"
KeyError: 'result'
```

**Comment by zadigre** [comment]
just to be sure I didn't do something wrong when downloading the file, I just tried it again... and I'm getting the same error.

**Comment by FuzzyMistborn** [comment]
Should I open a separate issue for US?

**Comment by cdnninja** [comment]
Yes please.   Also reference which brand as for USA they are separate.
