### ISSUE TITLE
Exception in update : 'resMsg' - traceback: Traceback

### ISSUE THREAD

**Issue by vonsh** [fuatakgun/kia_uvo#326]
Every few days my Kia integration fails to do a refresh (or a forced refresh). It will then log an error: 

Exception in update : 'resMsg' - traceback: Traceback

When that happens the Kia app is still able to update its data from the car. Reloading the integration will solve the issue for a while. Sometimes it also resolves itself. 

Debug logging:

`2022-04-30 05:00:00 DEBUG (SyncWorker_6) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Received forced vehicle data {'error': 'Key not authorized: Token is expired'}
2022-04-30 05:00:00 DEBUG (SyncWorker_6) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - get_stamp 2022-04-29 17:04:00.313000+00:[00 120000 358 998](tel:00 120000 358 998) 358.00360525
2022-04-30 05:00:00 DEBUG (SyncWorker_6) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get Vehicle Location {'error': 'Key not authorized: Token is expired'}
2022-04-30 05:00:00 WARNING (SyncWorker_6) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get vehicle location failed
2022-04-30 05:00:00 DEBUG (SyncWorker_7) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - get_stamp 2022-04-29 17:04:00.313000+00:[00 120000 358 998](tel:00 120000 358 998) 358.0050106416667
2022-04-30 05:00:01 DEBUG (SyncWorker_7) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - get_cached_vehicle_status response {'error': 'Key not authorized: Token is expired'}
2022-04-30 05:00:01 ERROR (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Exception in update : 'resMsg' - traceback: Traceback (most recent call last):
File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update
self.vehicle_data = await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 455, in get_cached_vehicle_status
return response["resMsg"]["vehicleStatusInfo"]
KeyError: 'resMsg'`

**Comment by cdnninja** [comment]
Believe this is solved in 2.0.   Due to age and how close we are to 2.0 leaving beta will close this.  Please reopen if having issues in 2.X
