### ISSUE TITLE
Exception in update : string indices must be integers

### ISSUE THREAD

**Issue by spacecowboy** [fuatakgun/kia_uvo#350]
**Region and Brand of car**

Europe, Kia e-Niro

**Describe the bug**
HomeAssistant log shows than an exception has been thrown

**Debug logs if an error occurred**

```
kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 455, in get_cached_vehicle_status return response["resMsg"]["vehicleStatusInfo"] TypeError: string indices must be integers
```

Have just now enable debug logs. Can update issue when they are logged

**Comment by Rothammel** [comment]
+1 same

**Comment by tschuchort** [comment]
+1

**Comment by hmmbob** [comment]
Same. I wonder if this is due to no information / no update from the vehicle, as I also have a different error in the logs just before the error above:

```py
2022-09-12 16:33:34.656 WARNING (SyncWorker_1) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get vehicle location failed
2022-09-12 16:34:44.022 ERROR (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last):
File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update
self.vehicle_data = await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 455, in get_cached_vehicle_status
return response["resMsg"]["vehicleStatusInfo"]
TypeError: string indices must be integers
```

**Comment by fuatakgun** [comment]
it is due to server not responded correctly, so this is a valid error but ti should not impact entities or states.

**Comment by cdnninja** [comment]
Interested to hear if this is still an issue in v2.0  Since this is close to leaving beta I will close this for now.  Please open a new issue if still a problem in 2.0
