### ISSUE TITLE
error in the log regarding AC and DC charge limits

### ISSUE THREAD

**Issue by zadigre** [fuatakgun/kia_uvo#387]
Canada, Kona Electric 2021

warning/errors in the logs regarding AC and DC charge limit. 
AC and DC charge limit entities in error also. 

2022-10-29 12:38:39.256 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 34.859 seconds (success: True)
2022-10-29 12:38:39.555 WARNING (MainThread) [homeassistant.components.number] custom_components.kia_uvo.number is setting deprecated attributes on an instance of NumberEntityDescription, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
2022-10-29 12:38:39.666 WARNING (MainThread) [homeassistant.components.number] custom_components.kia_uvo.number is setting deprecated attributes on an instance of NumberEntityDescription, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
2022-10-29 12:38:39.667 WARNING (MainThread) [homeassistant.components.number] custom_components.kia_uvo.number::HyundaiKiaChargingLimitNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
2022-10-29 12:38:39.686 WARNING (MainThread) [homeassistant.components.number] Entity None (<class 'custom_components.kia_uvo.number.HyundaiKiaChargingLimitNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom integration author.
2022-10-29 12:38:39.688 WARNING (MainThread) [homeassistant.components.number] Entity None (<class 'custom_components.kia_uvo.number.HyundaiKiaChargingLimitNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom integration author.
2022-10-29 12:38:39.694 ERROR (MainThread) [homeassistant.components.number] Error adding entities for domain number with platform kia_uvo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 352, in state
return self.value
File "/config/custom_components/kia_uvo/number.py", line 79, in value
return self._vehicle.ev_charge_limits.ac
AttributeError: 'NoneType' object has no attribute 'ac'
2022-10-29 12:38:39.705 ERROR (MainThread) [homeassistant.components.number] Error while setting up kia_uvo platform for number
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 352, in state
return self.value
File "/config/custom_components/kia_uvo/number.py", line 79, in value
return self._vehicle.ev_charge_limits.ac
AttributeError: 'NoneType' object has no attribute 'ac'

got this in the log right after restarting home assistant.

**Comment by cdnninja** [comment]
Which version?

**Comment by zadigre** [comment]
2.0.1

**Comment by cdnninja** [comment]
After you update to 2.0.2 could you let me know if you still have this error? You may need to delete the sensors that showed up.

**Comment by zadigre** [comment]
as mentioned in #391, 2.0.2 does not even start. it looks like something is missing. back to 2.0.1 for now.

**Comment by zadigre** [comment]
error no longer showing... and sensors are no longer there after deleting them and restarting HA.

**Comment by zadigre** [comment]
Are we supposed to get the charge limit numbers in Canada? That would be great if yes…

**Comment by cdnninja** [comment]
Should be able to add it in the underlying API if the raw data has the info. I would assume it does.

**Comment by cdnninja** [comment]
Any experience coding or interest in learning basics? Data mapping is something that is always of help and pretty straightforward to do.  Here is an example of it. https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/e6b309343a7f61c5d44452907716dfc083b1593e/hyundai_kia_connect_api/KiaUvoApiCA.py#L193-L195

**Comment by cdnninja** [comment]
I am going to close this out as the first error and key issue is fixed. Lets track the charge limits here as just saw you posted awhile back on this: #312

**Comment by zadigre** [comment]
> Should be able to add it in the underlying API if the raw data has the info. I would assume it does.

vehicle status data does not have this information. 
in the MyHyundai app, you have to go into View Charge Management. 



> Any experience coding or interest in learning basics? Data mapping is something that is always of help and pretty straightforward to do. Here is an example of it. https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/e6b309343a7f61c5d44452907716dfc083b1593e/hyundai_kia_connect_api/KiaUvoApiCA.py#L193-L195

my experience in coding is very very far... like programming Motorola 6809 and 68000 in assembly code in the late 90's 
I have no interest in learning basics for now... maybe later.  

> I am going to close this out as the first error and key issue is fixed. Lets track the charge limits here as just saw you posted awhile back on this: #312

yes this is me 😉 
it's just some kind of wishful thinking. I'm fine without this feature.

**Comment by cdnninja** [comment]
Happy to work on it if we can get the raw data.  And yes all good on the programming side. Thought I would check in if interested!  Thanks for all the help on 2.0!
