### ISSUE TITLE
USA Hyundai Missing sensors after upgrade to 2.0.5

### ISSUE THREAD

**Issue by afxefx** [fuatakgun/kia_uvo#397]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
USA and 2021 Hyundai Sonata N (ICE)

**Describe the bug**

Missing sensors after update to 2.0.5:

odometer
range_by_fuel
tire_pressure_front/rear_left/right
hood
set_temperature

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.m

Seeing the following in the logs:

`hyundai_kia_connect_api - Unable to get vehicle location: {'errorSubCode': 'C400_1', 'systemName': 'IDM', 'functionName': 'validatePIN', 'errorSubMessage': 'Missing Fields: blueLinkServicePin or pinToken', 'errorMessage': 'Please check to see that all required fields are populated and try again.', 'errorCode': 400, 'serviceName': 'CheckCustomerUserPin'}`

**To Reproduce**

Utilize 2.0.5

**Expected behavior**

Sensors to show

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
Location and tire pressure is hopefully fixed now.  Odometer and others are still going to be an issue.   

Could I get the debug logs of your json of the car? You are looking for this line followed be a wall of details.  Please remove any personal info like location. 

`get_cached_vehicle_status response`

**Comment by afxefx** [comment]
I added the debug line to my config under logger:

`custom_components.kia_uvo: debug`

I removed and re-added the integration but didn't receive the info that was requested.  All I received was the below after adding the integration back in:

`│2022-11-01 09:52:36.068 WARNING (SyncWorker_16) [hyundai_kia_connect_api.HyundaiBlueLinkAPIUSA] hyundai_kia_connect_api - Unable to get vehicle location: {'errorSubCode': 'C400_1', 'systemName': 'IDM', 'functionName': 'validatePIN', 'errorSubMessage': 'Missing Fields: blueLinkServicePin or pinToken', 'errorMessage': 'Please check to see that all required fields a│
re populated and try again.', 'errorCode': 400, 'serviceName': 'CheckCustomerUserPin'}                                                                                                                                                                                                                                                                                        │
│2022-11-01 09:52:38.397 WARNING (SyncWorker_15) [hyundai_kia_connect_api.HyundaiBlueLinkAPIUSA] hyundai_kia_connect_api - Unable to get vehicle location: {'errorSubCode': 'C400_1', 'systemName': 'IDM', 'functionName': 'validatePIN', 'errorSubMessage': 'Missing Fields: blueLinkServicePin or pinToken', 'errorMessage': 'Please check to see that all required fields a│
re populated and try again.', 'errorCode': 400, 'serviceName': 'CheckCustomerUserPin'}                                                                                                                                                                                                                                                                                        │
│2022-11-01 09:52:40.112 WARNING (SyncWorker_2) [hyundai_kia_connect_api.HyundaiBlueLinkAPIUSA] hyundai_kia_connect_api - Unable to get vehicle location: {'errorSubCode': 'C400_1', 'systemName': 'IDM', 'functionName': 'validatePIN', 'errorSubMessage': 'Missing Fields: blueLinkServicePin or pinToken', 'errorMessage': 'Please check to see that all required fields ar│
e populated and try again.', 'errorCode': 400, 'serviceName': 'CheckCustomerUserPin'}                                                                                                                                                                                                                                                                                         │
│2022-11-01 09:52:40.118 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 6.758 seconds (success: True)                                                                                                                                                                                                                           │
│2022-11-01 09:52:40.148 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.kia_uvo                                                                                                                                                                                                                                                          │
│2022-11-01 09:52:40.149 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.kia_uvo                                                                                                                                                                                                                                                                        │
│2022-11-01 09:52:40.150 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.kia_uvo                                                                                                                                                                                                                                                        │
│2022-11-01 09:52:40.152 INFO (MainThread) [homeassistant.components.lock] Setting up lock.kia_uvo                                                                                                                                                                                                                                                                            │
│2022-11-01 09:52:40.153 INFO (MainThread) [homeassistant.components.number] Setting up number.kia_uvo                                                                                                                                                                                                                                                                        │
│2022-11-01 09:52:40.166 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.2021_sonata_engine                                                                                                                                                                                                              │
│2022-11-01 09:52:40.172 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.2021_sonata_defrost                                                                                                                                                                                                             │
│2022-11-01 09:52:40.175 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.2021_sonata_steering_wheel_heater                                                                                                                                                                                               │
│2022-11-01 09:52:40.182 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.2021_sonata_back_window_heater                                                                                                                                                                                                  │
│2022-11-01 09:52:40.185 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.2021_sonata_front_left_door                                                                                                                                                                                                     │
│2022-11-01 09:52:40.188 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.2021_sonata_front_right_door                                                                                                                                                                                                    │
│2022-11-01 09:52:40.191 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.2021_sonata_back_left_door                                                                                                                                                                                                      │
│2022-11-01 09:52:40.195 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.2021_sonata_back_right_door                                                                                                                                                                                                     │
│2022-11-01 09:52:40.201 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.2021_sonata_trunk                                                                                                                                                                                                               │
│2022-11-01 09:52:40.204 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.2021_sonata_fuel_low_level                                                                                                                                                                                                      │
│2022-11-01 09:52:40.208 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.2021_sonata_tire_pressure_all                                                                                                                                                                                                   │
│2022-11-01 09:52:40.210 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.kia_uvo entity: binary_sensor.2021_sonata_air_conditioner                                                                                                                                                                                                     │
│2022-11-01 09:52:40.214 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.kia_uvo entity: sensor.2021_sonata_car_battery_level                                                                                                                                                                                                                 │
│2022-11-01 09:52:40.217 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.kia_uvo entity: sensor.2021_sonata_last_updated_at                                                                                                                                                                                                                   │
│2022-11-01 09:52:40.224 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new device_tracker.kia_uvo entity: device_tracker.2021_sonata_location                                                                                                                                                                                                          │
│2022-11-01 09:52:40.236 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new lock.kia_uvo entity: lock.2021_sonata_door_lock      `

**Comment by cdnninja** [comment]
Thank you.  Is location errors gone?

**Comment by benbohmer** [comment]
Works, I got confused by the reverse geocoding being removed(?).

**Comment by cdnninja** [comment]
geocoding is a good call out.   That needs to be re-added.  It wasn't so much removed just not re-written yet.

**Comment by cdnninja** [comment]
Could you see if 2.0.7 resolves the tire and hood sensors?  Out ones outstanding still.

**Comment by afxefx** [comment]
Hood sensor is now showing but the individual tire pressure sensors are not.  The "all" tire pressure sensor still shows correctly though.

**Comment by cdnninja** [comment]
Turns out a fix I thought I merged two days ago wasn't actually merged.   Explains my struggles. 2.0.8 has that fix.

**Comment by afxefx** [comment]
2.0.8 brought back the individual tire sensors just as you suspected it would.  Awesome work!  Let me know if I can be of assistance on the remaining missing sensors when you get to them.

**Comment by cdnninja** [comment]
Sounds good.  Last few will need a bit more work on my end since the data doesn't get returned under a typically call.  A second API call needs to be written.

**Comment by rindlerblabla** [comment]
The average consumption sensors introduced with PR https://github.com/fuatakgun/kia_uvo/pull/308 is now missing. (2.0.9)

**Comment by cdnninja** [comment]
> The average consumption sensors introduced with PR https://github.com/fuatakgun/kia_uvo/pull/308 is now missing. (2.0.9)

Are you able to open a new issue? That issue is a different region and different issue so will help me track.

**Comment by DJBenson** [comment]
> @DJBenson Assuming not USA Hyundai user can you please open a new issue and let us know the region you are in?
> 
> As for odometer please open a new item for that as well. Right now it should set to your home assistant settings but that may not be working. Are you from UK where they use miles?

Will do - sorry for the brevity of the above.

**Comment by cdnninja** [comment]
@afxefx  are you able to confirm what items are still missing for you? It looks to me like Odometer should work but may have been broken by the location issue.  I suspect temp may have issues because USA reports "low" when it isn't running. I have a fix coming for that.

**Comment by cdnninja** [comment]
Geolocation has been readded.

**Comment by afxefx** [comment]
@cdnninja sorry been working out of town.  Odometer, fuel range and temp are still missing for me. 

![image](https://user-images.githubusercontent.com/3475494/201490353-92178d05-8785-4bc4-8c45-1396a46d3d7b.png)

**Comment by cdnninja** [comment]
Could I get current logs from your car and any errors?

**Comment by afxefx** [comment]
Absolutely, logs below and I am running the latest version:

`homeassistant@hassio:~/.homeassistant $ grep "get_cached_vehicle_status" home-assistant.log
2022-11-13 12:24:56.475 DEBUG (SyncWorker_7) [hyundai_kia_connect_api.HyundaiBlueLinkAPIUSA] hyundai_kia_connect_api - get_cached_vehicle_status response {'hataTID': '0odkpxQSSR-YP4L4h15--A', 'vehicleStatus': {'dateTime': '2022-11-12T05:08:43Z', 'acc': False, 'fuelLevel': 46, 'defrostStatus': 'false', 'transCond': True, 'doorLockStatus': 'true', 'doorOpen': {'frontRight': 0, 'frontLeft': 0, 'backLeft': 0, 'backRight': 0}, 'washerFluidStatus': False, 'battery': {'powerAutoCutMode': 2, 'batSignalReferenceValue': {'batWarning': 65}, 'batSoc': 57, 'sjbDeliveryMode': 1}, 'seatHeaterVentInfo': {'rlSeatHeatState': 2, 'drvSeatHeatState': 2, 'rrSeatHeatState': 2, 'astSeatHeatState': 2}, 'vehicleLocation': {'coord': {'alt': 25.0, 'lon': xxx, 'type': 0, 'lat': xxx}}, 'ign3': False, 'ignitionStatus': 'false', 'lowFuelLight': False, 'sideBackWindowHeat': 0, 'dte': {'unit': 3, 'value': 174.0}, 'engine': False, 'remoteWaitingTimeAlert': {'remoteControlWaitingTime': 168, 'remoteControlAvailable': 1}, 'hoodOpen': False, 'breakOilStatus': False, 'vehicleMovementHis': True, 'airConditionStatus': 'false', 'smartKeyBatteryWarning': False, 'steerWheelHeat': 0, 'trunkOpen': False, 'doorLock': True, 'engineRuntime': {'unit': 3, 'value': 750}, 'airCtrlOn': False, 'airTemp': {'unit': 0, 'hvacTempType': 1, 'value': 'LO'}, 'lampWireStatus': {'headLamp': {'rightBifuncLamp': False, 'headLampStatus': False, 'leftLowLamp': False, 'rightHighLamp': False, 'leftBifuncLamp': False, 'leftHighLamp': False, 'rightLowLamp': False}, 'stopLamp': {'rightLamp': False, 'leftLamp': False}, 'turnSignalLamp': {'rightRearLamp': False, 'rightFrontLamp': False, 'leftRearLamp': False, 'leftFrontLamp': False}}, 'sleepModeCheck': True, 'defrost': False, 'tirePressureLamp': {'tirePressureWarningLampRearLeft': 0, 'tirePressureWarningLampFrontLeft': 0, 'tirePressureWarningLampFrontRight': 0, 'tirePressureWarningLampAll': 0, 'tirePressureWarningLampRearRight': 0}, 'trunkOpenStatus': 'false', 'engineOilStatus': False}}

2022-11-13 12:24:58.002 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.HyundaiBlueLinkAPIUSA] hyundai_kia_connect_api - get_cached_vehicle_status response {'hataTID': 'nAc1a9YsRaKpMnmbLXb9og', 'vehicleStatus': {'dateTime': '2022-11-12T05:08:43Z', 'acc': False, 'fuelLevel': 46, 'defrostStatus': 'false', 'transCond': True, 'doorLockStatus': 'true', 'doorOpen': {'frontRight': 0, 'frontLeft': 0, 'backLeft': 0, 'backRight': 0}, 'washerFluidStatus': False, 'battery': {'powerAutoCutMode': 2, 'batSignalReferenceValue': {'batWarning': 65}, 'batSoc': 57, 'sjbDeliveryMode': 1}, 'seatHeaterVentInfo': {'rlSeatHeatState': 2, 'drvSeatHeatState': 2, 'rrSeatHeatState': 2, 'astSeatHeatState': 2}, 'vehicleLocation': {'coord': {'alt': 25.0, 'lon': xxx, 'type': 0, 'lat': xxx}}, 'ign3': False, 'ignitionStatus': 'false', 'lowFuelLight': False, 'sideBackWindowHeat': 0, 'dte': {'unit': 3, 'value': 174.0}, 'engine': False, 'remoteWaitingTimeAlert': {'remoteControlWaitingTime': 168, 'remoteControlAvailable': 1}, 'hoodOpen': False, 'breakOilStatus': False, 'vehicleMovementHis': True, 'airConditionStatus': 'false', 'smartKeyBatteryWarning': False, 'steerWheelHeat': 0, 'trunkOpen': False, 'doorLock': True, 'engineRuntime': {'unit': 3, 'value': 750}, 'airCtrlOn': False, 'airTemp': {'unit': 0, 'hvacTempType': 1, 'value': 'LO'}, 'lampWireStatus': {'headLamp': {'rightBifuncLamp': False, 'headLampStatus': False, 'leftLowLamp': False, 'rightHighLamp': False, 'leftBifuncLamp': False, 'leftHighLamp': False, 'rightLowLamp': False}, 'stopLamp': {'rightLamp': False, 'leftLamp': False}, 'turnSignalLamp': {'rightRearLamp': False, 'rightFrontLamp': False, 'leftRearLamp': False, 'leftFrontLamp': False}}, 'sleepModeCheck': True, 'defrost': False, 'tirePressureLamp': {'tirePressureWarningLampRearLeft': 0, 'tirePressureWarningLampFrontLeft': 0, 'tirePressureWarningLampFrontRight': 0, 'tirePressureWarningLampAll': 0, 'tirePressureWarningLampRearRight': 0}, 'trunkOpenStatus': 'false', 'engineOilStatus': False}}`

**Comment by cdnninja** [comment]
Are you able to look for the following line? https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/14714bda1c08dcf2a33d7e3ed0ec6fd2f4adbb6b/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py#L357

"Get Vehicles Response"

For some reason your status above doesn't contain this "vehicleDetails" https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/14714bda1c08dcf2a33d7e3ed0ec6fd2f4adbb6b/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py#L144

this should be giving you the extra fields required for things like Odometer and range remaining.  As both aren't in the standard call for USA Hyundai.   I have to assume I have a mistake in my call but the logs for "get vehicles response" will help confirm. 

As for temp - I need to spend some time seeing what is going on with that one.  As it is listed above just not as a number but rather as LO.

**Comment by afxefx** [comment]
My apologies on that last log and here is the requested log:

`homeassistant@hassio:~/.homeassistant $ grep "Get Vehicles Response" home-assistant.log
2022-11-13 14:49:01.358 DEBUG (SyncWorker_5) [hyundai_kia_connect_api.HyundaiBlueLinkAPIUSA] hyundai_kia_connect_api - Get Vehicles Response {"enrolledVehicleDetails":[{"packageDetails":[{"assetNumber":"xxx","displayCategory":"Connected Care","packageId":"xxx","term":"xxx","renewalDate":"xxx","packageType":"Connected Care","startDate":"xxx"},{"assetNumber":"xxx","displayCategory":"Remote","packageId":"xxx","term":"xxx","renewalDate":"xxx","packageType":"Remote","startDate":"xxx"},{"assetNumber":"xxx","displayCategory":"Guidance","packageId":"xxx","term":"xxx","renewalDate":"xxx","packageType":"Guidance","startDate":"xxx"}],"vehicleDetails":{"svrStatus":"NONE","dynamicBurgerMenu":"https://owners.hyundaiusa.com/content/dam/hyundai/us/myhyundai/image/2021/sonata/n-line/exterior/base/shimmering-silver-pearl/Dashboard-01.png/jcr:content/renditions/cq5dam.thumbnail.105.68.png","remoteStartWakeupDays":"seven","enrollmentDate":"xxx","svdDay":"11","trim":"N LINE","modelCode":"SONATA","ubiCapabilityInd":"Y","vin":"xxx","enrollmentId":"xxx","sideMirrorHeatCapable":"YES","ownersuccession":"1","odometer":"8733","nickName":"2021 SONATA","defaultBurgerMenu":"https://owners.hyundaiusa.com/content/dam/hyundai/us/myhyundai/image/2021/sonata/n-line/exterior/base/default/Dashboard-01.png/jcr:content/renditions/cq5dam.thumbnail.105.68.png","evStatus":"N","modelYear":"2021","steeringWheelHeatCapable":"YES","defaultDashboard":"https://owners.hyundaiusa.com/content/dam/hyundai/us/myhyundai/image/2021/sonata/n-line/exterior/base/default/Dashboard-01.png","vehicleGeneration":"2","starttype":"BUTTON","sapColorCode":"R2T","bluelinkEnabled":true,"odometerUpdateDate":"20221111205840","fatcAvailable":"Y","color":"SILVER","maintSyncCapable":"YES","brandIndicator":"H","deviceStatus":"ENROLLED","setOffPeak":"0","mapProvider":"HERE","generalBurgerMenu":"https://owners.hyundaiusa.com/content/dam/hyundai/us/myhyundai/image/2021/sonata/general/exterior/base/default/Dashboard-01.png/jcr:content/renditions/cq5dam.thumbnail.105.68.png","interiorColor":"RBP","accessoryCode":"WAVN 5.0","nadid":"xxx","mit":"7500","regid":"xxx","blueLink":"Y","waypointInd":"YES","billingInd":"xxx","seatConfigurations":{"seatConfigs":[{"heatingCapable":"YES","ventCapable":"NO","supportedLevels":"2,6,7,8","seatLocationID":"1"},{"heatingCapable":"YES","ventCapable":"NO","supportedLevels":"2,6,7,8","seatLocationID":"2"}]},"dynamicDashboard":"https://owners.hyundaiusa.com/content/dam/hyundai/us/myhyundai/image/2021/sonata/n-line/exterior/base/shimmering-silver-pearl/Dashboard-01.png","imat":"7500","additionalVehicleDetails":{"combinedHeatSettingsEnable":"Y","temperatureRange":"false","tmuSleepMode":"No","enableHCAModule":"Y","hyundaiHome":"N","wifiHotspotCapable":"N","remoteLockConsentForRemoteStart":"No","calendarVehicleSyncEnable":"Yes","dkEnrolled":"N","icpAvntCapable":"N","icpAACapable":"N","dkType":"","enableRoadSideAssitanceAAAModule":"Y","evAlarmOptionInfo":"No","remoteLockConsentForRemoteStartCapable":"No","mapOtaAccepted":"N","icpCPCapable":"N","dkCapable":"N","enableValetActivate":"N","energyConsoleCapable":"No"},"transmissiontype":"AUTO","bluelinkEnrolled":true,"setChargeSchedule":"0","rearWindowHeatCapable":"YES","preferredDealerCode":"xxx","hmaModel":"DN8","series":"SONATA","enrollmentStatus":"ACTIVE","generalDashboard":"https://owners.hyundaiusa.com/content/dam/hyundai/us/myhyundai/image/2021/sonata/general/exterior/base/default/Dashboard-01.png","userprofilestatus":"Y"},"roleDetails":[{"roleCode":"OWN","roleName":"OWNER"},{"roleCode":"SUB","roleName":"SUBSCRIBER"}],"responseHeaderMap":{}}],"addressDetails":[{"city":"xxx","street":"xxx","postalCode":"xx","type":"PRIMARY","region":"xx"}],"user":{"accountId":"xx","firstName":"xx","lastName":"xx","phonesOptIn":[{"number":"xxx","primaryPhoneIndicator":"YES","fccOptIn":"","type":"MOBILE"}],"loginId":"xxx","additionalUserDetails":{"userProfileUpdate":"Y","timezoneOffset":-5,"billingAccountNumber":"xxx","appRating":"N","timezoneAbbr":"EST","otaAcceptance":"N","telematicsPhoneNumber":"xxx"},"tncFlag":"N","phones":[{"number":"xxx","type":"cell","order":1}],"idmId":"xxx","userId":"xxx","notificationEmail":"xxx","email":"xxx"}}`

**Comment by cdnninja** [comment]
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/123 resolves the odometer part.  Since you seem pretty familiar with HA are you able to edit the manifest file in the integration and bump to API version 1.39.3 to test if temp and odometer are fixed? 

As for range - does your mobile app show this?  I don't see it anywhere in the logs you provided.

**Comment by afxefx** [comment]
Made the manifest change and restarted, logs follow:

`Error setting up entry Hyundai USA xxx for kia_uvo
Traceback (most recent call last):
  File "/srv/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/home/homeassistant/.homeassistant/custom_components/kia_uvo/coordinator.py", line 102, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/venv_3.9.7/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 80, in check_and_force_update_vehicles
    self.update_vehicle_with_cached_state(vehicle)
  File "/srv/homeassistant/venv_3.9.7/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 63, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/srv/homeassistant/venv_3.9.7/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 154, in update_vehicle_with_cached_state
    state = self._get_cached_vehicle_state(token, vehicle)
  File "/srv/homeassistant/venv_3.9.7/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 145, in _get_cached_vehicle_state
    if vehicle.odometer < get_child_value(vehicle_status["vehicleDetails"], "odometer.value"):
TypeError: '<' not supported between instances of 'str' and 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/kia_uvo/__init__.py", line 40, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/srv/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 178, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: '<' not supported between instances of 'str' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.homeassistant/custom_components/kia_uvo/__init__.py", line 42, in async_setup_entry
    raise ConfigEntryNotReady(f"Config Not Ready: {ex}")
NameError: name 'ConfigEntryNotReady' is not defined`

`Unexpected error fetching kia_uvo data: '<' not supported between instances of 'str' and 'NoneType'
Traceback (most recent call last):
  File "/srv/homeassistant/venv_3.9.7/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/home/homeassistant/.homeassistant/custom_components/kia_uvo/coordinator.py", line 102, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/venv_3.9.7/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 80, in check_and_force_update_vehicles
    self.update_vehicle_with_cached_state(vehicle)
  File "/srv/homeassistant/venv_3.9.7/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 63, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/srv/homeassistant/venv_3.9.7/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 154, in update_vehicle_with_cached_state
    state = self._get_cached_vehicle_state(token, vehicle)
  File "/srv/homeassistant/venv_3.9.7/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 145, in _get_cached_vehicle_state
    if vehicle.odometer < get_child_value(vehicle_status["vehicleDetails"], "odometer.value"):
TypeError: '<' not supported between instances of 'str' and 'NoneType'`

The fuel range was present prior to the v2 version change if I recall correctly and here's a screenshot of my mobile app:
![Screenshot_20221114-203541](https://user-images.githubusercontent.com/3475494/201807859-a8d0896a-175c-4c8e-b065-05ad17b5a945.png)

**Comment by cdnninja** [comment]
1.39.4 should fix that next error.   I will dig through the old code to see if I can learn where that data came from.

**Comment by afxefx** [comment]
Odometer has returned.  Thanks for your work and let me know if you need anything further from me, always willing to help.

**Comment by cdnninja** [comment]
In theory I found where that data should be in the old version but it isn't in your logs.  Would you be willing to remove and readd with the old version to confirm it exists?   It would remove historical data.   I am guessing the above screenshot is done within app based on fuel remaining.

**Comment by afxefx** [comment]
Sure thing although I won't be able to do so until tomorrow, thanks again.

**Comment by cdnninja** [comment]
I just noticed that on a separate issue another Hyundai USA user has the location for range in the logs.   I will put this on my to do list to implement for this region.   You don't seem to currently have the data though. https://github.com/fuatakgun/kia_uvo/issues/436#issuecomment-1312634084

**Comment by cdnninja** [comment]
The initial issue with the PIN should also now be resolved in 2.0.29.

**Comment by afxefx** [comment]
Had a chance to rollback to 1.8.5 which added 5, maybe 6, additional sensors:

![Screenshot_20221115-194420](https://user-images.githubusercontent.com/3475494/202055941-2dd3f24b-0c24-42e0-9185-48bbf06ebe77.png)
![Screenshot_20221115-194503](https://user-images.githubusercontent.com/3475494/202055959-e476b888-16f0-46a0-95c6-46e8663bd66b.png)

**Comment by cdnninja** [comment]
So looks like we need:

Washer Fluid Warning
Smart Key Battery Warning
Range by Fuel (odd, I know the path though so will add and see if it works!)
Data(Was intentionally removed as an attempt to be a native HA integration - can re-add though.

I think that is all?

**Comment by afxefx** [comment]
That sounds like the lot of it to me as well.  Here for testing when necessary and thanks again.

**Comment by cdnninja** [comment]
Could you give 2.0.31 a go? Should have everything else except the data one.

**Comment by afxefx** [comment]
All showing except fuel range lol

**Comment by afxefx** [comment]
In HyundaiBlueLinkAPIUSA.py, is line 278 a duplicate of 165 and causing the fuel value to be overwritten by the EV value (which I don't have)?

**Comment by cdnninja** [comment]
Good find v2.0.32 adds if statements to this that should resolve.

**Comment by afxefx** [comment]
That did it!  Looking good from my side and thanks again for your perseverance and persistence. 

![image](https://user-images.githubusercontent.com/3475494/202522125-5d54688c-4cbb-4957-9738-3b25d471e3af.png)

**Comment by cdnninja** [comment]
Thanks for sticking with it!
