### ISSUE TITLE
Lock issue

### ISSUE THREAD

**Issue by CVHvisuals** [fuatakgun/kia_uvo#405]
Failed to call service lock/lock. 'HyundaiBlueLinkAP|USA' object has no attribute 'username'

will not lock
V 2.0.10 US

**Comment by cdnninja** [comment]
2.0.11 should resolve this.  Thanks for testing this out for us!

**Comment by CVHvisuals** [comment]
I'm getting the same result with v2.0.11
2022 Tucson US

**Comment by cdnninja** [comment]
Could I get logs referencing line numbers?

**Comment by CVHvisuals** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/kia_uvo/coordinator.py:109 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 12:15:44 AM (6 occurrences) 
Last logged: 12:58:02 AM

[547873893072] 'HyundaiBlueLinkAPIUSA' object has no attribute 'username'
[547848767568] 'HyundaiBlueLinkAPIUSA' object has no attribute 'username'
[547845611168] 'HyundaiBlueLinkAPIUSA' object has no attribute 'username'
[547812268240] 'HyundaiBlueLinkAPIUSA' object has no attribute 'username'
[548061610192] 'HyundaiBlueLinkAPIUSA' object has no attribute 'username'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/kia_uvo/lock.py", line 51, in async_lock
    await self.coordinator.async_lock_vehicle(self.vehicle.id)
  File "/config/custom_components/kia_uvo/coordinator.py", line 109, in async_lock_vehicle
    await self.hass.async_add_executor_job(self.vehicle_manager.lock, vehicle_id)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 103, in lock
    return self.api.lock_action(self.token, self.get_vehicle(vehicle_id), VEHICLE_LOCK_ACTION.LOCK)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 382, in lock_action
    data = {"userName": self.username, "vin": vehicle.VIN}
AttributeError: 'HyundaiBlueLinkAPIUSA' object has no attribute 'username'

**Comment by CVHvisuals** [comment]
Logger: hyundai_kia_connect_api.HyundaiBlueLinkAPIUSA
Source: /usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py:312 
First occurred: 12:45:28 AM (1 occurrences) 
Last logged: 12:45:28 AM

hyundai_kia_connect_api - Unable to get vehicle location: {'errorSubCode': 'C400_1', 'systemName': 'IDM', 'functionName': 'validatePIN', 'errorSubMessage': 'Missing Fields: blueLinkServicePin or pinToken', 'errorMessage': 'Please check to see that all required fields are populated and try again.', 'errorCode': 400, 'serviceName': 'CheckCustomerUserPin'}

**Comment by cdnninja** [comment]
My mistake. Looks like my change didn't save.   Please retry on the latest.  I will look at the location item after confirming locks work.

**Comment by CVHvisuals** [comment]
The service call to lock now works, although, the status is always showing “Unlocked”. Since it always shows unlocked, it only sends a lock command, even when it is already locked. 

It is very responsive now.

**Comment by cdnninja** [comment]
Great.  Are you still having a location issue?

**Comment by cdnninja** [comment]
As for showing lock this is probably a refresh issue that I am working on.  I have noticed this with my native app as well.  To send the opposite you can use the service in the developer menu.
