### ISSUE TITLE
Charging limit not working anymore

### ISSUE THREAD

**Issue by rindlerblabla** [fuatakgun/kia_uvo#411]
EU EV6

**Describe the bug**
Since 2.0 it is not possible to set charging limit anymore.

> 
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/kia_uvo/coordinator.py:137
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 15:02:17 (2 occurrences)
Last logged: 15:02:24

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: VehicleManager.set_charge_limits() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 98, in async_handle_set_charge_limit
    await coordinator.set_charge_limits(
  File "/config/custom_components/kia_uvo/coordinator.py", line 137, in set_charge_limits
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: VehicleManager.set_charge_limits() takes 3 positional arguments but 4 were given

**Comment by cdnninja** [comment]
Could you retry on the latest?

**Comment by rindlerblabla** [comment]
Unfortunately it is still not working. Causing error:

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/kia_uvo/services.py:100
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 07:51:52 (2 occurrences)
Last logged: 07:53:17

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: HyundaiKiaConnectDataUpdateCoordinator.set_charge_limits() missing 1 required positional argument: 'dc_limit'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 100, in async_handle_set_charge_limit
    await coordinator.set_charge_limits(
TypeError: HyundaiKiaConnectDataUpdateCoordinator.set_charge_limits() missing 1 required positional argument: 'dc_limit'

**Comment by cdnninja** [comment]
Are you able to retest with latest?

**Comment by rindlerblabla** [comment]
Thanks for helping out. Now (2.0.20) I get the error:

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/kia_uvo/coordinator.py:143
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 08:19:51 (1 occurrences)
Last logged: 08:19:51

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: '3f967574c7ae6ad38156bd48b4ae5006'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 100, in async_handle_set_charge_limit
    await coordinator.set_charge_limits(
  File "/config/custom_components/kia_uvo/coordinator.py", line 143, in set_charge_limits
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 114, in set_charge_limits
    return self.api.set_charge_limits(self.token, self.get_vehicle(vehicle_id), limits)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 54, in get_vehicle
    return self.vehicles[vehicle_id]
KeyError: '3f967574c7ae6ad38156bd48b4ae5006'

**Comment by cdnninja** [comment]
Could you now try v2.0.22?

**Comment by cdnninja** [comment]
Thanks for testing this beta release.  Really appreciate it.  This is key to getting feature parity and helping push this project to the next level!
