### ISSUE TITLE
Door lock not working: Object of type VEHICLE_LOCK_ACTION is not JSON serializable

### ISSUE THREAD

**Issue by svdstra** [fuatakgun/kia_uvo#445]
### Discussed in https://github.com/fuatakgun/kia_uvo/discussions/433

<div type='discussions-op-text'>

<sup>Originally posted by **svdstra** November 12, 2022</sup>
When activating in home assistant the door lock I receive the following message: "Object of type VEHICLE_LOCK_ACTION is not JSON serializable".
Any idea how to handle this?

I am located in EU and the brand is Kia.

Thanks, Sander

Version 2.0.26
Logging:
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/kia_uvo/coordinator.py:137
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:56:41 (2 occurrences)
Last logged: 14:13:13

[140682695160400] Object of type VEHICLE_LOCK_ACTION is not JSON serializable
[140681824778080] Object of type VEHICLE_LOCK_ACTION is not JSON serializable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/kia_uvo/lock.py", line 54, in async_unlock
    await self.coordinator.async_unlock_vehicle(self.vehicle.id)
  File "/config/custom_components/kia_uvo/coordinator.py", line 137, in async_unlock_vehicle
    await self.hass.async_add_executor_job(self.vehicle_manager.unlock, vehicle_id)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 109, in unlock
    return self.api.lock_action(self.token, self.get_vehicle(vehicle_id), VEHICLE_LOCK_ACTION.UNLOCK)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 438, in lock_action
    response = requests.post(url, json=payload, headers=headers).json()
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 412, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/site-packages/simplejson/encoder.py", line 272, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type VEHICLE_LOCK_ACTION is not JSON serializable
</div>

**Comment by cdnninja** [comment]
Could you try the latest update and let me know how it goes?

**Comment by svdstra** [comment]
Thank you for your answer!
Unfortunately with version  2.0.32 I get this result in the log and the
lock/unlock action still does not work:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/kia_uvo/coordinator.py:133
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:43:09 (3 occurrences)
Last logged: 21:45:04

[139946034638624] Object of type VEHICLE_LOCK_ACTION is not JSON
serializable
Traceback (most recent call last):
  File
"/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py",
line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in
async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in
_execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]],
handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py",
line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678,
in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943,
in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715,
in _handle_entity_call
    await result
  File "/config/custom_components/kia_uvo/lock.py", line 51, in async_lock
    await self.coordinator.async_lock_vehicle(self.vehicle.id)
  File "/config/custom_components/kia_uvo/coordinator.py", line 133, in
async_lock_vehicle
    await self.hass.async_add_executor_job(self.vehicle_manager.lock,
vehicle_id)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58,
in run
    result = self.fn(*self.args, **self.kwargs)
  File
"/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py",
line 107, in lock
    return self.api.lock_action(self.token, self.get_vehicle(vehicle_id),
VEHICLE_LOCK_ACTION.LOCK)
  File
"/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py",
line 436, in lock_action
    response = requests.post(url, json=payload, headers=headers)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115,
in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59,
in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line
573, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line
484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line
371, in prepare
    self.prepare_body(data, files, json)
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line
511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py",
line 412, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/site-packages/simplejson/encoder.py",
line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/site-packages/simplejson/encoder.py",
line 378, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/site-packages/simplejson/encoder.py",
line 272, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type VEHICLE_LOCK_ACTION is not JSON serializable

Op do 17 nov. 2022 om 21:37 schreef cdnninja ***@***.***>:

**Comment by cdnninja** [comment]
Could you try v2.0.33?

**Comment by svdstra** [comment]
Yes, it works!!!
Thank you verry much for your great effort!!!!

Sander

Op do 17 nov. 2022 23:55 schreef cdnninja ***@***.***>:

**Comment by cdnninja** [comment]
Thanks for testing and raising this!
