### ISSUE TITLE
start_climate TypeError

### ISSUE THREAD

**Issue by Mauin** [fuatakgun/kia_uvo#447]
When calling `kia_uvo.start_climate` I see the following error (Kia EV6 in EU). This happens both when configuring an e.g. Button to call the service and from the developer tools.

kia_uvo v2.0.33

Service call config:
```
service: kia_uvo.start_climate
data:
  device_id: <device_id>
  climate: true
  temperature: 21
```

Error:
```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/kia_uvo/coordinator.py:145
Integration: Hyundai / Kia Connect ([documentation](https://github.com/fuatakgun/kia_uvo), [issues](https://github.com/fuatakgun/kia_uvo/issues))
First occurred: November 20, 2022 at 9:37:15 PM (10 occurrences)
Last logged: 8:44:32 AM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 66, in async_handle_start_climate
    await coordinator.async_start_climate(vehicle_id, climate_request_options)
  File "/config/custom_components/kia_uvo/coordinator.py", line 145, in async_start_climate
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 101, in start_climate
    return self.api.start_climate(self.token, self.get_vehicle(vehicle_id), options)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 468, in start_climate
    "heating1": int(options.heating),
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by Mauin** [comment]
The core issue seems to be that "heating" is effectively a required argument when looking through the code, but it is not in the UI.

When selecting: "Heating: Off" / `heating: "0"` the call succeeds. 

[This](https://github.com/fuatakgun/kia_uvo/blob/1aa30ea0aaeae4a7f09ae6743bb94f5a6728f913/custom_components/kia_uvo/Vehicle.py#L191) maps heating to `False` if unset which is then converted to `int(heating)` [here](https://github.com/fuatakgun/kia_uvo/blob/master/custom_components/kia_uvo/KiaUvoApiEU.py#L609).

Looks like the arg should either be marked as required in the UI or the mapping should map heating to `0`.

**Comment by cdnninja** [comment]
Thanks for this!  I have dropped a PR in the API to set defaults.  I will drop a second PR to make this required in our YAML.
