### ISSUE TITLE
Exception kia_uvo login : 'redirectUrl' - new Hyundai-Account

### ISSUE THREAD

**Issue by grblmpfh** [fuatakgun/kia_uvo#56]
I have created two new hyundai accounts but when I try to install kia_uvo with them it fails with the following error/log:

2021-08-10 14:49:44 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get Device ID request {'ccsp-service-id': '6d477c38-3ca4-4cf3-9557-2a1929a94654', 'Stamp': 'fWILIMmJ...V6YC9BI=', 'Content-Type': 'application/json;charset=UTF-8', 'Host': 'prd.eu-ccapi.hyundai.com:8080', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.12.0'} {'pushRegId': 'cS0...A8j5B', 'pushType': 'GCM', 'uuid': '3daa...b4ff9a'}
2021-08-10 14:49:44 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get Device ID response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'deviceId': 'f980e146-4202-41d1-9be9-436a3faf90b3'}, 'msgId': '4c503cf7-0000-0000-0000-c20d000000'}
2021-08-10 14:49:44 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get cookies request https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/authorize?response_type=code&state=test&client_id=000000000-3ca4-4cf3-9557-000000000000&redirect_uri=https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/redirect&lang=en
2021-08-10 14:49:45 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get cookies response {'TS0154565f': '01cba...b36a7dc', 'account': 'ZDJjZD...de7ac938f'}
2021-08-10 14:49:45 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Sign In Response {'errId': '33a0...e347', 'errCode': '4003', 'errMsg': 'Invalid values', 'errBody': {'userId': '', 'remainCount': 4, 'remainTime': 300}}
2021-08-10 14:49:45 ERROR (MainThread) [custom_components.kia_uvo.config_flow] kia_uvo Exception in kia_uvo login : 'redirectUrl' - traceback: Traceback (most recent call last):
File "/config/custom_components/kia_uvo/config_flow.py", line 150, in async_step_user
self.token = await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 150, in login
parsed_url = urlparse(response.json()["redirectUrl"])
KeyError: 'redirectUrl'

Any hints?

**Comment by kvisle** [comment]
I have the exact same problem with my EU Hyundai Bluelink-account.

**Comment by fuatakgun** [comment]
so, you both created new accounts and shared your car with new account and you are receiving this error?

**Comment by grblmpfh** [comment]
Yes. I have two accounts: a main one and a shared one. Both receiving this error. I did not have a former BlueLink account, so there was no migration necessary.

**Comment by kvisle** [comment]
I have a single account, I did log out and in, and it is giving me this error.
My account is pretty new (but I don't know when the cutoff for old vs. new were) - March this year. I haven't seen any indication of migration going on after logging off/on bluelink.  (The car is shared with a different account too)

I have not yet waited 24 hours to see if the problem persists (I didn't read the instructions correctly in README.md)

**Comment by StHeinemann** [comment]
Hi.
I got the same error. 
Hyundai Ioniq (not the 5). New Hyundai Account since some month. Logout and Login in Bluelink App works.
Don't share car. This is my main account. 
Location is EU, Germany 

This is from home assistant log:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:164
Integration: Kia Uvo / Hyundai Bluelink (documentation)
First occurred: 9:56:18 (10 occurrences)
Last logged: 10:38:17

kia_uvo Exception in kia_uvo login : 'redirectUrl' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 150, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 150, in login parsed_url = urlparse(response.json()["redirectUrl"]) KeyError: 'redirectUrl'
kia_uvo Exception in kia_uvo login : 'result' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 150, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiCA.py", line 63, in login response = response["result"] KeyError: 'result'

**Comment by cdnninja** [comment]
@StHeinemann  I assume that is two separate errors from separate attempts?  The second one looks to be using the canada selection not EU.

**Comment by kvisle** [comment]
FWIW, these are the logs from my latest attempt (masked UUIDs and tokens in case they can be abused in some way):

```
2021-08-15 22:14:36 DEBUG (SyncWorker_5) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get Device ID request {'ccsp-service-id': '6d477c38-XXXX-XXXX-XXXX-2a1929a94654', 'Stamp': 'fWILIMmJNU........j2021-08-15 22:14:36 DEBUG (SyncWorker_5) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get Device ID request {'ccsp-service-id': '6d477c38-XXXX-XXXX-XXXX-2a1929a94654', 'Stamp': 'fWILIMmJNU........j37hW6AH+RM=', 'Content-Type': 'application/json;charset=UTF-8', 'Host': 'prd.eu-ccapi.hyundai.com:8080', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.12.0'} {'pushRegId': 'c4sMSchs5HY...........SpkwMNu2ms_5rLxThimR5gtvh3m', 'pushType': 'GCM', 'uuid': 'e421beba-XXXX-XXXX-XXXX-1cb5031c138a'}
2021-08-15 22:14:36 DEBUG (SyncWorker_5) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get Device ID response {'retCode': 'S', 'resCode': '0000', 'resMsg': {'deviceId': 'f178f0d8-XXXX-XXXX-XXXX-16d0f4c334ff'}, 'msgId': '30590fb4-56c9-45ae-bd96-5f4a17a738ef'}
2021-08-15 22:14:36 DEBUG (SyncWorker_5) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get cookies request https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/authorize?response_type=code&state=test&client_id=6d477c38-XXXX-XXXX-XXXX-2a1929a94654&redirect_uri=https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/redirect&lang=en
2021-08-15 22:14:37 DEBUG (SyncWorker_5) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get cookies response {'TS0154565f': '01cbaa6f703198392ef9279..........2ff4f6622f5e970177d', 'account': 'NzU5MzNh......4b80c1a42e'}
2021-08-15 22:14:37 DEBUG (SyncWorker_5) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Sign In Response {'errId': '053589c8-0d9a-47d5-9e8d-adf9ed9a2b4e', 'errCode': '4003', 'errMsg': 'Invalid values', 'errBody': {'userId': '', 'remainCount': 4, 'remainTime': 300}}
2021-08-15 22:14:37 ERROR (MainThread) [custom_components.kia_uvo.config_flow] kia_uvo Exception in kia_uvo login : 'redirectUrl' - traceback: Traceback (most recent call last):
File "/config/custom_components/kia_uvo/config_flow.py", line 150, in async_step_user
self.token = await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 150, in login
parsed_url = urlparse(response.json()["redirectUrl"])
KeyError: 'redirectUrl'
```

**Comment by fuatakgun** [comment]
> @StHeinemann I assume that is two separate errors from separate attempts? The second one looks to be using the canada selection not EU.

Agree on this, are you sure you have picked correct region?

General comment: I am on vacation for 2 more weeks but I will be happy to debug this issue if you can share your car with me.

**Comment by StHeinemann** [comment]
Sorry for late reply.
Yes, there were two errros. I have mixed something up. Sorry, again.

This is logging from an actaul try:

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:164
Integration: Kia Uvo / Hyundai Bluelink (documentation)
First occurred: 21:25:24 (1 occurrences)
Last logged: 21:25:24

kia_uvo Exception in kia_uvo login : 'redirectUrl' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 150, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 150, in login parsed_url = urlparse(response.json()["redirectUrl"]) KeyError: 'redirectUrl'

**Comment by sunkan85** [comment]
it could be that you are using a hyundai account now and not a bluelink account? It satt to me wrong pass/acc

**Comment by StHeinemann** [comment]
> it could be that you are using a hyundai account now and not a bluelink account? It satt to me wrong pass/acc

Hi. Thanks. That was the problem. I used the password for my hyundai accuount. I have  tried the old passwort for the bluelink now and that works. I'm a bit connfuesed, because I thoguht it is the same acoount. But the old bluelink ist still allive.

**Comment by grblmpfh** [comment]
But this does not solve the problem, because some of us never had a bluelink account.

**Comment by sunkan85** [comment]
Yes, I bought my car 3 weeks ago and now you can only make a Hyundai
account, so I can not use this add-on

Den sön 29 aug. 2021 16:51grblmpfh ***@***.***> skrev:

**Comment by grblmpfh** [comment]
That is why i explicitly put "new Hyundai account" in the title. There already was an almost identical issue for the transitioned bluelink accounts but those have different causes!

**Comment by fuatakgun** [comment]
I will be able to support/debug these issues after vacation if you can share your car with me

**Comment by kvisle** [comment]
Hm, but is it still possible to register a bluelink-account if you do not have one? Because that would be my problem. I registered a Hyundai-account in March.

**Comment by danharvey** [comment]
This might be related to a change from the EU Hyundai servers that now require a stamp to sign which changes weekly. The Bluelinky project run a library in the Android app to generate these regularly but this is quiet hacky: https://github.com/Hacksore/bluelinky#custom-stamps

It's probably possible to re-use some of the logic they've done here!

**Comment by fuatakgun** [comment]
I am getting help from their stamps over here : https://github.com/fuatakgun/kia_uvo/blob/bf7d5ea2aeff776be5968e565183d10489c4f6d4/custom_components/kia_uvo/KiaUvoApiEU.py#L51

**Comment by fuatakgun** [comment]
I am waiting confirmation from one of the users, so I can create an account and debug the code on their account.

**Comment by grblmpfh** [comment]
What kind of confirmation do you need? To share the car I would need a (your) phone number to share with. But you would need a hyundai account first, which has to be linked with that phone number. 

And I have to admit that I am not happy to share a car my life is depending on without fully understanding the consequences...

**Comment by fuatakgun** [comment]
Someone offered me to share the car, so I want to have a 1-1 meeting before doing this. I actually would not prefer if this might have consequences as life threatening. Can you elaborate a bit more on this?

**Comment by fuatakgun** [comment]
I had just created a new hyundai account now and able to login, of course there was no car under that account, so integration failed later on, But at least, I moved forward. Let's take a step backward and try with these;
- be sure that you had migrated your account from Bluelink to Hyundai
- logout from mobile app and relogin with known credentials
- try again with the integration
- if above failes, please create a new account from scratch and share your car with it. I had issues (rarely) so I needed to try couple of times.

**Comment by kvisle** [comment]
@fuatakgun have had temporary access to our car through bluelink and have sent me screenshots from Home Assistant with our car added. Looks very promising, and I'm excited to try this out 👍

**Comment by fuatakgun** [comment]
hi all, let me update here and close this for goodness. To resolve this issue, I need one `problematic` account as the login sequence is different for `migrated` accounts vs `new/fresh` accounts and I do not want to get any credentials of anyone and I do not want to consume time on this, because; it is very easy to resolve. Create a new/fresh/not used email account with Hyundai and share your car with new account. I prefer to consume time to improve existing integration, rather than solving the problem, which can be avoided with fallback solution.

**Comment by fuatakgun** [comment]
more details;
- there are fresh/new accounts - no problem here
- there are old accounts which are migrated. there is a different login sequence happening behind the scenes and to find out correct login sequence, I had to install a `poked` app (I poked it :)) and receive all traffic. that being said, my account was bran new and never hit the old sequence. to find out legacy way, I need a real account from a real person and I am avoiding asking this because; 1/we have a workaround in place 2/it is too much to share with a stranger 3/it is too much to be hold responsible for it.

**Comment by Flight777** [comment]
@fuatakgun 
I just tried with my wife's account who I shared to car with, but I'm having the same issue as described here (same with my account):

https://github.com/SondreNjaastad/node-red-contrib-bluelinky/issues/56

Both accounts are complete fresh/new, we never owned a Hyundai or Kia before.
